server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bishmie/smart_parking_system.git
          default-label: main
          username: bishmie


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/